In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATA_PATH = '/content/drive/MyDrive/workspace/VPBank_Hackathon/src/Data'

In [ ]:
crm_call_center_file = "CRM Call Center Logs.csv"
crm_events_file = "CRM Events.csv"
crm_review_file = "CRM Reviews.csv"
luxury_loan_portfolio_file = "LuxuryLoanPortfolio.csv"
completed_acct_file = "completedacct.csv"
completed_card_file = "completedcard.csv"
completed_client_file = "completedclient.csv"
completed_disposition_file = "completeddisposition.csv"
completed_loan_file = "completedloan.csv"
completed_district_file = "completeddistrict.csv"
completed_order_file = "completedorder.csv"
completed_trans_file = "completedtrans.csv"

In [ ]:
crm_call_center_df = pd.read_csv(os.path.join(DATA_PATH, crm_call_center_file))
crm_events_df = pd.read_csv(os.path.join(DATA_PATH, crm_events_file))
crm_users_df = pd.read_csv(os.path.join(DATA_PATH, crm_review_file),  encoding='unicode_escape')
luxury_loan_portfolio_df = pd.read_csv(os.path.join(DATA_PATH, luxury_loan_portfolio_file))
completed_acct_df = pd.read_csv(os.path.join(DATA_PATH, completed_acct_file))
completed_card_df = pd.read_csv(os.path.join(DATA_PATH, completed_card_file))
completed_client_df = pd.read_csv(os.path.join(DATA_PATH, completed_client_file))
completed_disposition_df = pd.read_csv(os.path.join(DATA_PATH, completed_disposition_file))
completed_loan_df = pd.read_csv(os.path.join(DATA_PATH, completed_loan_file))
completed_district_df = pd.read_csv(os.path.join(DATA_PATH, completed_district_file))
completed_order_df = pd.read_csv(os.path.join(DATA_PATH, completed_order_file))
completed_trans_df = pd.read_csv(os.path.join(DATA_PATH, completed_trans_file))

In [ ]:
max(completed_loan_df['fulldate'])

'2018-12-08'

In [ ]:
completed_loan_df['account_id'].value_counts()

account_id
A00003354    1
A00004981    1
A00003556    1
A00003562    1
A00009645    1
            ..
A00000002    1
A00007401    1
A00004533    1
A00009208    1
A00007542    1
Name: count, Length: 682, dtype: int64

In [ ]:
completed_order_df

      order_id account_id bank_to  account_to  amount           k_symbol
0        29401  A00000001      YZ    87144583  2452.0  Household Payment
1        29402  A00000002      ST    89597016  3372.7       Loan Payment
2        29403  A00000002      QR    13943797  7266.0  Household Payment
3        29404  A00000003      WX    83084338  1135.0  Household Payment
4        29405  A00000003      CD    24485939   327.0
...        ...        ...     ...         ...     ...                ...
6466     46334  A00011362      YZ    70641225  4780.0  Household Payment
6467     46335  A00011362      MN    78507822    56.0
6468     46336  A00011362      ST    40799850   330.0  Insurance Payment
6469     46337  A00011362      KL    20009470   129.0
6470     46338  A00011362      MN    61540514  5392.0       Loan Payment

[6471 rows x 6 columns]

In [ ]:
completed_trans_df['operation']

0          Credit in Cash
1          Credit in Cash
2          Credit in Cash
3          Credit in Cash
4          Credit in Cash
                ...
1056315               NaN
1056316               NaN
1056317               NaN
1056318               NaN
1056319               NaN
Name: operation, Length: 1056320, dtype: object

In [ ]:
max(completed_card_df['fulldate'])

'2018-12-29'

In [ ]:
luxury_loan_portfolio_df

,loan_id,funded_amount,funded_date,duration years,duration months,10 yr treasury index date funded,interest rate percent,interest rate,payments,total past payments,...,BUILDING CLASS AT PRESENT,ADDRESS 1,ADDRESS 2,ZIP CODE,CITY,STATE,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,TAX CLASS AT TIME OF SALE
0,LL0000076,790000.0,2012-04-27,20,240,1.96,3.359,0.03359,4524.65,92,...,R1,171 SOUTH 9TH STREET,9,10001,New York City,NY,1,0,0,2
1,LL0000151,1720000.0,2014-10-14,15,180,2.21,3.508,0.03508,12302.74,62,...,R3,1242 E 80TH ST,19,10104,New York City,NY,1,0,0,1
2,LL0000161,3720000.0,2014-06-07,15,180,2.60,3.896,0.03896,27322.92,66,...,R3,1884 53RD STREET,2,10029,New York City,NY,1,0,0,1
3,LL0000175,1079000.0,2012-02-23,20,240,1.99,3.389,0.03389,6196.40,94,...,R1,79 EAGLE STREET,6,10010,New York City,NY,1,0,0,2
4,LL0000178,2028000.0,2016-04-01,20,240,1.79,3.188,0.03188,11439.05,45,...,RW,34 NORTH 7TH STREET,5,10172,New York City,NY,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,LL0001228,528000.0,2012-11-10,20,240,1.61,3.010,0.03009,2930.65,85,...,R6,1554 49TH STREET,1,10158,New York City,NY,1,0,0,1
1674,LL0001358,885000.0,2015-08-16,20,240,2.20,3.599,0.03599,5177.78,52,...,R6,1554 49TH STREET,2,10108,New York City,NY,1,0,0,1
1675,LL0001479,1530000.0,2014-09-01,20,240,2.35,3.749,0.03748,9069.60,64,...,R6,1554 49TH STREET,3,10166,New York City,NY,1,0,0,1
1676,LL0001561,897000.0,2014-02-14,15,180,2.75,4.049,0.04049,6657.05,70,...,RR,828 BEDFORD AVENUE,2,10081,New York City,NY,11,0,16376,2
1677,LL0001674,1656000.0,2016-07-12,15,180,1.53,2.828,0.02828,11299.54,41,...,R8,828 BEDFORD AVENUE,1,10022,New York City,NY,1,0,0,2

In [ ]:
luxury_loan_portfolio_df.columns

Index(['loan_id', 'funded_amount', 'funded_date', 'duration years',
       'duration months', '10 yr treasury index date funded',
       'interest rate percent', 'interest rate', 'payments',
       'total past payments', 'loan balance', 'property value', 'purpose',
       'firstname', 'middlename', 'lastname', 'social', 'phone', 'title',
       'employment length', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS 1', 'ADDRESS 2', 'ZIP CODE',
       'CITY', 'STATE', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET',
       'TAX CLASS AT TIME OF SALE'],
      dtype='object')

In [ ]:
completed_acct_df

     account_id  district_id         frequency  parseddate  year  month  day
0     A00000576           55  Monthly Issuance  2013-01-01  2013      1    1
1     A00003818           74  Monthly Issuance  2013-01-01  2013      1    1
2     A00000704           55  Monthly Issuance  2013-01-01  2013      1    1
3     A00002378           16  Monthly Issuance  2013-01-01  2013      1    1
4     A00002632           24  Monthly Issuance  2013-01-02  2013      1    2
...         ...          ...               ...         ...   ...    ...  ...
4495  A00000124           55  Monthly Issuance  2017-12-28  2017     12   28
4496  A00003958           59  Monthly Issuance  2017-12-28  2017     12   28
4497  A00000777           30  Monthly Issuance  2017-12-28  2017     12   28
4498  A00001573           63  Monthly Issuance  2017-12-29  2017     12   29
4499  A00003276            1  Monthly Issuance  2017-12-29  2017     12   29

[4500 rows x 7 columns]

In [ ]:
group_account_trans_df = completed_trans_df.groupby(by=['account_id', 'k_symbol', 'type']).agg({'amount': 'sum', 'fulldate': 'count'})

In [ ]:
group_account_trans_df =group_account_trans_df.reset_index()

In [ ]:
group_account_trans_df['money_pre_month'] = group_account_trans_df['amount'] / group_account_trans_df['fulldate']

In [ ]:
group_account_trans_df

,account_id,k_symbol,type,amount,fulldate,money_pre_month
0,A00000001,Household,Debit,98080.0,40,2452.000000
1,A00000001,Interest Credited,Credit,3065.5,45,68.122222
2,A00000001,Payment on Statement,Debit,584.0,40,14.600000
3,A00000002,Household,Debit,472290.0,65,7266.000000
4,A00000002,Interest Credited,Credit,10717.5,70,153.107143
...,...,...,...,...,...,...
15630,A00011362,Loan Payment,Debit,129408.0,24,5392.000000
15631,A00011362,Payment on Statement,Debit,481.8,33,14.600000
15632,A00011382,Interest Credited,Credit,11026.5,80,137.831250
15633,A00011382,Payment on Statement,Debit,511.0,35,14.600000
15634,A00011382,Sanction Interest,Debit,20.4,8,2.550000

In [ ]:
group_account_trans_df['k_symbol'].value_counts()

k_symbol
Interest Credited       4453
Payment on Statement    4396
Household               3297
                        1293
Old Age Pension          740
Loan Payment             682
Insurance Payment        510
Sanction Interest        264
Name: count, dtype: int64

In [ ]:
# len(completed_trans_df[(completed_trans_df['account_id'] == 'A00000001') & (completed_trans_df['k_symbol'] == 'Payment on Statement')])

In [ ]:
completed_order_df['k_symbol'].value_counts()

k_symbol
Household Payment    3502
                     1379
Loan Payment          717
Insurance Payment     532
Leasing Payment       341
Name: count, dtype: int64

In [ ]:
completed_order_df

      order_id account_id bank_to  account_to  amount           k_symbol
0        29401  A00000001      YZ    87144583  2452.0  Household Payment
1        29402  A00000002      ST    89597016  3372.7       Loan Payment
2        29403  A00000002      QR    13943797  7266.0  Household Payment
3        29404  A00000003      WX    83084338  1135.0  Household Payment
4        29405  A00000003      CD    24485939   327.0
...        ...        ...     ...         ...     ...                ...
6466     46334  A00011362      YZ    70641225  4780.0  Household Payment
6467     46335  A00011362      MN    78507822    56.0
6468     46336  A00011362      ST    40799850   330.0  Insurance Payment
6469     46337  A00011362      KL    20009470   129.0
6470     46338  A00011362      MN    61540514  5392.0       Loan Payment

[6471 rows x 6 columns]

In [ ]:
completed_card_df['type'].value_counts()

type
VISA Signature    659
VISA Standard     145
VISA Infinite      88
Name: count, dtype: int64

In [ ]:
order_map_trans = {
    'Household Payment': 'Household',
    'Loan Payment': 'Loan Payment',
    'Insurance Payment': 'Insurance Payment'
}

trans_map_order = {
    'Household': 'Household Payment',
    'Loan Payment': 'Loan Payment',
    'Insurance Payment': 'Insurance Payment'
}

In [ ]:
account_order = completed_order_df['account_id'].unique().tolist()

In [ ]:
accounts = []
count = 0
df_check = None
for idx, row in group_account_trans_df.iterrows():
    account_id = row['account_id']
    k_symbol_trans = row['k_symbol']
    amount_per_month = row['money_pre_month']
    if account_id in account_order:
      df_temp = completed_order_df[(completed_order_df['account_id'] == account_id) & (completed_order_df['amount'] == amount_per_month)]
      if df_check is None:
        df_check = df_temp
      else:
        df_check = pd.concat([df_check, df_temp])
      count += 1

In [194]:
cash_in_df = completed_trans_df[completed_trans_df['bank'].isna()].groupby(by=['account_id']).agg({'amount': 'sum', 'trans_id': 'count'}).reset_index()
cash_in_df.rename({'amount': 'amount_cash_in', 'trans_id': 'trans_cash_in_count'}, axis=1, inplace=True)
cash_out_df = completed_trans_df[~completed_trans_df['bank'].isna()].groupby(by=['account_id']).agg({'amount': 'sum', 'trans_id': 'count'}).reset_index()
cash_out_df.rename({'amount': 'amount_cash_out', 'trans_id': 'trans_cash_out_count'}, axis=1, inplace=True)

In [195]:
cash_in_df

     account_id  amount_cash_in  trans_cash_in_count
0     A00000001        111539.5                  154
1     A00000002       1060308.5                  319
2     A00000003        230008.8                   78
3     A00000004         63357.4                   93
4     A00000005         34206.4                   51
...         ...             ...                  ...
4495  A00011333       3295795.5                  368
4496  A00011349       1293458.2                  184
4497  A00011359       1175264.8                  223
4498  A00011362       1020572.5                  184
4499  A00011382       1281969.9                  213

[4500 rows x 3 columns]

In [196]:
cash_out_df

     account_id  amount_cash_out  trans_cash_out_count
0     A00000001         263635.0                    85
1     A00000002        2091170.8                   159
2     A00000003          65013.0                    39
3     A00000004         287614.0                    93
4     A00000005         132675.0                    33
...         ...              ...                   ...
3707  A00011328          23370.0                     5
3708  A00011349        2663914.0                   120
3709  A00011359        1772816.6                   155
3710  A00011362         309438.0                   160
3711  A00011382        1341192.0                    40

[3712 rows x 3 columns]

In [ ]:
completed_order_df[~completed_order_df['order_id'].isin(df_check['order_id'].unique())]

      order_id account_id bank_to  account_to  amount           k_symbol
1        29402  A00000002      ST    89597016  3372.7       Loan Payment
14       29415  A00000010      QR    93182509  1344.0    Leasing Payment
15       29416  A00000011      ST    38470870  2132.0  Household Payment
38       29442  A00000030      EF    66168540  2480.2    Leasing Payment
41       29445  A00000034      WX    21845197  1479.0    Leasing Payment
...        ...        ...     ...         ...     ...                ...
6438     45974  A00011138      YZ    73215025  3744.7       Loan Payment
6439     45978  A00011141      QR    68096905  3744.7       Loan Payment
6460     46289  A00011333      IJ    99705963  3286.7    Leasing Payment
6467     46335  A00011362      MN    78507822    56.0
6469     46337  A00011362      KL    20009470   129.0

[1002 rows x 6 columns]

In [ ]:
completed_trans_df[(completed_trans_df['account_id'] == 'A00000002') & (completed_trans_df['amount'] == 3372.7)]

,column_a,trans_id,account_id,type,operation,amount,balance,k_symbol,bank,account,year,month,day,fulldate,fulltime,fulldatewithtime,date
31658,31659,T00000361,A00000002,Debit,Remittance to Another Bank,3372.7,35337.9,Loan Payment,Capital One,89597016.0,2014,1,12,2014-01-12,13:37:43,2014-01-12T13:37:43,2014-01-12
39503,39504,T00000362,A00000002,Debit,Remittance to Another Bank,3372.7,29636.0,Loan Payment,Capital One,89597016.0,2014,2,12,2014-02-12,08:39:57,2014-02-12T08:39:57,2014-02-12
45265,45266,T00000363,A00000002,Debit,Remittance to Another Bank,3372.7,35826.9,Loan Payment,Capital One,89597016.0,2014,3,12,2014-03-12,11:30:57,2014-03-12T11:30:57,2014-03-12
51676,51677,T00000364,A00000002,Debit,Remittance to Another Bank,3372.7,40638.9,Loan Payment,Capital One,89597016.0,2014,4,12,2014-04-12,14:08:36,2014-04-12T14:08:36,2014-04-12
58415,58416,T00000365,A00000002,Debit,Remittance to Another Bank,3372.7,42771.5,Loan Payment,Capital One,89597016.0,2014,5,12,2014-05-12,13:55:03,2014-05-12T13:55:03,2014-05-12
65909,65910,T00000366,A00000002,Debit,Remittance to Another Bank,3372.7,40008.8,Loan Payment,Capital One,89597016.0,2014,6,12,2014-06-12,16:44:40,2014-06-12T16:44:40,2014-06-12
73547,73548,T00000367,A00000002,Debit,Remittance to Another Bank,3372.7,35317.3,Loan Payment,Capital One,89597016.0,2014,7,12,2014-07-12,15:03:34,2014-07-12T15:03:34,2014-07-12
81026,81027,T00000368,A00000002,Debit,Remittance to Another Bank,3372.7,40521.5,Loan Payment,Capital One,89597016.0,2014,8,12,2014-08-12,13:45:15,2014-08-12T13:45:15,2014-08-12
88734,88735,T00000369,A00000002,Debit,Remittance to Another Bank,3372.7,42446.9,Loan Payment,Capital One,89597016.0,2014,9,12,2014-09-12,13:19:32,2014-09-12T13:19:32,2014-09-12
96668,96669,T00000370,A00000002,Debit,Remittance to Another Bank,3372.7,35327.6,Loan Payment,Capital One,89597016.0,2014,10,12,2014-10-12,08:59:54,2014-10-12T08:59:54,2014-10-12
104904,104905,T00000371,A00000002,Debit,Remittance to Another Bank,3372.7,41640.6,Loan Payment,Capital One,89597016.0,2014,11,12,2014-11-12,11:11:15,2014-11-12T11:11:15,2014-11-12
113793,113794,T00000372,A00000002,Debit,Remittance to Another Bank,3372.7,47779.5,Loan Payment,Capital One,89597016.0,2014,12,12,2014-12-12,11:28:30,2014-12-12T11:28:30,2014-12-12
125907,125908,T00000373,A00000002,Debit,Remittance to Another Bank,3372.7,36211.0,Loan Payment,Capital One,89597016.0,2015,1,12,2015-01-12,15:49:00,2015-01-12T15:49:00,2015-01-12
138675,138676,T00000374,A00000002,Debit,Remittance to Another Bank,3372.7,30012.1,Loan Payment,Capital One,89597016.0,2015,2,12,2015-02-12,16:01:09,2015-02-12T16:01:09,2015-02-12
147536,147537,T00000375,A00000002,Debit,Remittance to Another Bank,3372.7,37704.9,Loan Payment,Capital One,89597016.0,2015,3,12,2015-03-12,12:34:27,2015-03-12T12:34:27,2015-03-12
156946,156947,T00000376,A00000002,Debit,Remittance to Another Bank,3372.7,43222.4,Loan Payment,Capital One,89597016.0,2015,4,12,2015-04-12,14:24:12,2015-04-12T14:24:12,2015-04-12
166611,166612,T00000377,A00000002,Debit,Remittance to Another Bank,3372.7,35525.5,Loan Payment,Capital One,89597016.0,2015,5,12,2015-05-12,16:55:56,2015-05-12T16:55:56,2015-05-12
176978,176979,T00000378,A00000002,Debit,Remittance to Another Bank,3372.7,42748.5,Loan Payment,Capital One,89597016.0,2015,6,12,2015-06-12,14:40:20,2015-06-12T14:40:20,2015-06-12
187662,187663,T00000379,A00000002,Debit,Remittance to Another Bank,3372.7,46202.3,Loan Payment,Capital One,89597016.0,2015,7,12,2015-07-12,12:35:38,2015-07-12T12:35:38,2015-07-12
198217,198218,T00000380,A00000002,Debit,Remittance to Another Bank,3372.7,47546.7,Loan Payment,Capital One,89597016.0,2015,8,12,2015-08-12,14:34:40,2015-08-12T14:34:40,2015-08-12
209113,209114,T00000381,A00000002,Debit,Remittance to Another Bank,3372.7,30879.2,Loan Payment,Capital One,89597016.0,2015,9,12,2015-09-12,08:15:55,2015-09-12T08:15:55,2015-09-12
220258,220259,T00000382,A00000002,Debit,Remittance to Another Bank,3372.7,38971.7,Loan Payment,Capital One,89597016.0,2015,10,12,2015-10-12,13:29:12,2015-10-12T13:29:12,2015-10-12
231857,231858,T00000383,A00000002,Debit,Remittance to Another Bank,3372.7,36440.2,Loan Payment,Capital One,89597016.0,2015,11,12,2015-11-12,13:53:37,2015-11-12T13:53:37,2015-11-12
244387,244388,T00000384,A00000002,Debit,Remittance to Another Bank,3372.7,54774.2,Loan Payment,Capital One,89597016.0,2015,12,12,2015-12-12,13:08:37,2015-12-12T13:08:37,2015-12-12

In [ ]:
completed_trans_df['operation'].value_counts()

operation
Cash Withdrawal                 434918
Remittance to Another Bank      208283
Credit in Cash                  156743
Collection from Another Bank     65226
Credit Card Withdrawal            8036
Name: count, dtype: int64

In [ ]:
completed_trans_df[completed_trans_df['operation']=='Collection from Another Bank']

,column_a,trans_id,account_id,type,operation,amount,balance,k_symbol,bank,account,year,month,day,fulldate,fulltime,fulldatewithtime,date
15,16,T00637742,A00002177,Credit,Collection from Another Bank,5123.0,5923.0,Old Age Pension,State Street Corp.,62457513.0,2013,1,5,2013-01-05,16:44:42,2013-01-05T16:44:42,2013-01-05
17,18,T00232961,A00000793,Credit,Collection from Another Bank,3401.0,4201.0,NaN,Goldman Sachs,6149286.0,2013,1,5,2013-01-05,11:56:11,2013-01-05T11:56:11,2013-01-05
21,22,T00542216,A00001844,Credit,Collection from Another Bank,3242.0,3742.0,NaN,Capital One,42988401.0,2013,1,7,2013-01-07,10:11:45,2013-01-07T10:11:45,2013-01-07
24,25,T00579374,A00001972,Credit,Collection from Another Bank,5298.0,5698.0,Old Age Pension,Bank of New York Mellon Corp.,14132887.0,2013,1,7,2013-01-07,08:09:01,2013-01-07T08:09:01,2013-01-07
46,47,T01049882,A00003592,Credit,Collection from Another Bank,6007.0,6607.0,Old Age Pension,U.S. Bancorp,73166322.0,2013,1,10,2013-01-10,09:02:13,2013-01-10T09:02:13,2013-01-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047119,1047120,T00551866,A00001879,Credit,Collection from Another Bank,3039.0,18013.6,NaN,TD Bank,19752383.0,2018,12,14,2018-12-14,11:59:55,2018-12-14T11:59:55,2018-12-14
1047121,1047122,T00549190,A00001871,Credit,Collection from Another Bank,34552.0,59688.1,NaN,Wells Fargo & Co.,39485311.0,2018,12,14,2018-12-14,11:50:33,2018-12-14T11:50:33,2018-12-14
1047122,1047123,T00546460,A00001860,Credit,Collection from Another Bank,3255.0,20916.3,NaN,U.S. Bancorp,61854898.0,2018,12,14,2018-12-14,15:59:23,2018-12-14T15:59:23,2018-12-14
1047127,1047128,T00605757,A00002062,Credit,Collection from Another Bank,64642.0,97552.6,NaN,Citigroup,10179949.0,2018,12,14,2018-12-14,10:36:37,2018-12-14T10:36:37,2018-12-14
1047137,1047138,T00519257,A00001773,Credit,Collection from Another Bank,4316.0,17215.9,Old Age Pension,Bank of America,77385341.0,2018,12,14,2018-12-14,08:15:18,2018-12-14T08:15:18,2018-12-14

In [ ]:
last_trans_account = completed_trans_df.drop_duplicates(subset='account_id', keep='last')

In [ ]:
first_trans_account = completed_trans_df.drop_duplicates(subset='account_id', keep='first')

In [ ]:
trans_account_synthesis = pd.merge(first_trans_account, last_trans_account, on='account_id', how='inner', suffixes= ('_first', '_last'))

In [ ]:
trans_account_synthesis['fulldate_last_pre'] = pd.to_datetime(trans_account_synthesis['fulldate_last'], format='%Y-%m-%d')
trans_account_synthesis['fulldate_first_pre'] = pd.to_datetime(trans_account_synthesis['fulldate_first'], format='%Y-%m-%d')
trans_account_synthesis['diff_date'] = (trans_account_synthesis['fulldate_last_pre'] - trans_account_synthesis['fulldate_first_pre']).dt.days

In [ ]:
columns_used = ['account_id', 'balance_last', 'diff_date','date_last']
trans_last_synthesis_df = trans_account_synthesis[columns_used]

In [ ]:
luxury_loan_portfolio_df.head(5)

,loan_id,funded_amount,funded_date,duration years,duration months,10 yr treasury index date funded,interest rate percent,interest rate,payments,total past payments,...,BUILDING CLASS AT PRESENT,ADDRESS 1,ADDRESS 2,ZIP CODE,CITY,STATE,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,TAX CLASS AT TIME OF SALE
0,LL0000076,790000.0,2012-04-27,20,240,1.96,3.359,0.03359,4524.65,92,...,R1,171 SOUTH 9TH STREET,9,10001,New York City,NY,1,0,0,2
1,LL0000151,1720000.0,2014-10-14,15,180,2.21,3.508,0.03508,12302.74,62,...,R3,1242 E 80TH ST,19,10104,New York City,NY,1,0,0,1
2,LL0000161,3720000.0,2014-06-07,15,180,2.60,3.896,0.03896,27322.92,66,...,R3,1884 53RD STREET,2,10029,New York City,NY,1,0,0,1
3,LL0000175,1079000.0,2012-02-23,20,240,1.99,3.389,0.03389,6196.40,94,...,R1,79 EAGLE STREET,6,10010,New York City,NY,1,0,0,2
4,LL0000178,2028000.0,2016-04-01,20,240,1.79,3.188,0.03188,11439.05,45,...,RW,34 NORTH 7TH STREET,5,10172,New York City,NY,1,0,0,4

In [ ]:
luxury_loan_portfolio_df['phone']

0       542-843-5089
1       625-614-0118
2       255-592-5290
3       757-337-7073
4       478-573-2416
            ...
1673    341-197-7229
1674    915-662-1564
1675    387-918-8796
1676    794-476-6508
1677    944-832-7169
Name: phone, Length: 1678, dtype: object

In [ ]:
luxury_loan_portfolio_df['firstname']

0          Devin
1          Rhett
2            Jax
3       Nicholas
4          Riley
          ...
1673        King
1674       Mason
1675       Tyson
1676      Ximena
1677    Jonathan
Name: firstname, Length: 1678, dtype: object

In [ ]:
luxury_loan_portfolio_df['lastname']

0         Walters
1        Calderon
2        Richards
3          Priest
4         Hoffman
          ...
1673     Saunders
1674      Robbins
1675    Maldonado
1676     Marshall
1677         Jean
Name: lastname, Length: 1678, dtype: object

In [ ]:
luxury_loan_portfolio_df.social

0       972-69-4236
1       577-13-5838
2       263-55-1721
3       512-60-5121
4       271-64-4634
           ...
1673    118-82-8393
1674    134-32-0424
1675    361-45-1730
1676    274-93-0056
1677    607-32-8064
Name: social, Length: 1678, dtype: object

In [ ]:
completed_client_df

,client_id,sex,fulldate,day,month,year,age,social,first,middle,last,phone,email,address_1,address_2,city,state,zipcode,district_id
0,C00000001,Female,1990-12-13,13,12,1990,29,926-93-2157,Emma,Avaya,Smith,367-171-6840,emma.smith@gmail.com,387 Wellington Ave.,Unit 1,Albuquerque,NM,47246,18
1,C00000002,Male,1965-02-04,4,2,1965,54,806-94-5725,Noah,Everest,Thompson,212-423-7734,noah.thompson@gmail.com,75 W. Berkshire St.,NaN,New York City,NY,10040,1
2,C00000003,Female,1960-10-09,9,10,1960,59,614-70-9100,Olivia,Brooklynne,Johnson,212-425-6932,olivia.johnson@outlook.com,36 Second St.,NaN,New York City,NY,10162,1
3,C00000004,Male,1976-12-01,1,12,1976,43,580-20-3414,Liam,Irvin,White,951-567-8925,liam.white@gmail.com,7607 Sunnyslope Street,NaN,Indianapolis,IN,49047,5
4,C00000005,Female,1980-07-03,3,7,1980,39,536-14-5809,Sophia,Danae,Williams,428-265-1568,sophia.williams@gmail.com,755 Galvin Street,NaN,Indianapolis,IN,40852,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,C00013955,Female,1965-10-30,30,10,1965,54,830-38-3530,Adrianna,Jillian,Moore,212-205-7422,adrianna.moore@outlook.com,9405 SW. Leeton Ridge Drive,NaN,New York City,NY,10121,1
5365,C00013956,Male,1963-04-06,6,4,1963,56,773-25-4409,Aaron,Roman,Park,212-645-8820,aaron.park@gmail.com,7021 Chapel Ave.,NaN,New York City,NY,10118,1
5366,C00013968,Male,1988-04-13,13,4,1988,31,227-17-0778,Eli,Leonardo,Warner,508-465-5164,eli.warner@hotmail.com,43 Edgemont Dr.,NaN,Fall River,MA,2721,61
5367,C00013971,Female,1982-10-19,19,10,1982,37,278-77-3298,Ruth,Joy,Martin,856-636-3840,ruth.martin@gmail.com,7087 E. Pennsylvania Street,Unit 8,Danbury,CT,48475,67
5368,C00013998,Female,1973-08-12,12,8,1973,46,266-21-2541,Miriam,Abby,Jackson,431-633-5403,miriam.jackson@gmail.com,29 Buckingham Rd.,NaN,Chicago,IL,44244,74

In [ ]:
df_merge_test = pd.merge(completed_client_df, luxury_loan_portfolio_df, on='social', how='inner')

In [ ]:
luxury_loan_portfolio_df.columns

Index(['loan_id', 'funded_amount', 'funded_date', 'duration years',
       'duration months', '10 yr treasury index date funded',
       'interest rate percent', 'interest rate', 'payments',
       'total past payments', 'loan balance', 'property value', 'purpose',
       'firstname', 'middlename', 'lastname', 'social', 'phone', 'title',
       'employment length', 'BUILDING CLASS CATEGORY', 'TAX CLASS AT PRESENT',
       'BUILDING CLASS AT PRESENT', 'ADDRESS 1', 'ADDRESS 2', 'ZIP CODE',
       'CITY', 'STATE', 'TOTAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET',
       'TAX CLASS AT TIME OF SALE'],
      dtype='object')

In [ ]:
luxury_loan_portfolio_df.title

0       Vice President Global Field Services
1                    Senior program manager
2                                        NaN
3                              Vice presiden
4                             Bank examiner
                        ...
1673                         franchise owner
1674                 Chief Operating Officer
1675                         Owner/physician
1676                          General Manger
1677         Vice President, Capital Markets
Name: title, Length: 1678, dtype: object

In [ ]:
df_merge_loan = pd.merge(completed_loan_df, luxury_loan_portfolio_df, on='loan_id', how='inner')

In [ ]:
df_merge_loan

Empty DataFrame
Columns: [loan_id, account_id, amount, duration, payments_x, status, year, month, day, fulldate, location, purpose_x, funded_amount, funded_date, duration years, duration months, 10 yr treasury index date funded, interest rate percent, interest rate, payments_y, total past payments, loan balance, property value, purpose_y, firstname, middlename, lastname, social, phone, title, employment length, BUILDING CLASS CATEGORY, TAX CLASS AT PRESENT, BUILDING CLASS AT PRESENT, ADDRESS 1, ADDRESS 2, ZIP CODE, CITY, STATE, TOTAL UNITS, LAND SQUARE FEET, GROSS SQUARE FEET, TAX CLASS AT TIME OF SALE]
Index: []

[0 rows x 43 columns]

In [ ]:
completed_loan_df[completed_loan_df['loan_id']=="L0000076"]

Empty DataFrame
Columns: [loan_id, account_id, amount, duration, payments, status, year, month, day, fulldate, location, purpose]
Index: []

In [ ]:
completed_acct_df

     account_id  district_id         frequency  parseddate  year  month  day
0     A00000576           55  Monthly Issuance  2013-01-01  2013      1    1
1     A00003818           74  Monthly Issuance  2013-01-01  2013      1    1
2     A00000704           55  Monthly Issuance  2013-01-01  2013      1    1
3     A00002378           16  Monthly Issuance  2013-01-01  2013      1    1
4     A00002632           24  Monthly Issuance  2013-01-02  2013      1    2
...         ...          ...               ...         ...   ...    ...  ...
4495  A00000124           55  Monthly Issuance  2017-12-28  2017     12   28
4496  A00003958           59  Monthly Issuance  2017-12-28  2017     12   28
4497  A00000777           30  Monthly Issuance  2017-12-28  2017     12   28
4498  A00001573           63  Monthly Issuance  2017-12-29  2017     12   29
4499  A00003276            1  Monthly Issuance  2017-12-29  2017     12   29

[4500 rows x 7 columns]

In [ ]:
completed_disposition_df

        disp_id  client_id account_id   type
0     D00000001  C00000001  A00000001  Owner
1     D00000002  C00000002  A00000002  Owner
2     D00000003  C00000003  A00000002   User
3     D00000004  C00000004  A00000003  Owner
4     D00000005  C00000005  A00000003   User
...         ...        ...        ...    ...
5364  D00013647  C00013955  A00011349  Owner
5365  D00013648  C00013956  A00011349   User
5366  D00013660  C00013968  A00011359  Owner
5367  D00013663  C00013971  A00011362  Owner
5368  D00013690  C00013998  A00011382  Owner

[5369 rows x 4 columns]

In [ ]:
completed_trans_df

,column_a,trans_id,account_id,type,operation,amount,balance,k_symbol,bank,account,year,month,day,fulldate,fulltime,fulldatewithtime,date
0,1,T00695247,A00002378,Credit,Credit in Cash,700.0,700.0,NaN,NaN,NaN,2013,1,1,2013-01-01,11:02:40,2013-01-01T11:02:40,2013-01-01
1,2,T00171812,A00000576,Credit,Credit in Cash,900.0,900.0,NaN,NaN,NaN,2013,1,1,2013-01-01,08:23:33,2013-01-01T08:23:33,2013-01-01
2,3,T00207264,A00000704,Credit,Credit in Cash,1000.0,1000.0,NaN,NaN,NaN,2013,1,1,2013-01-01,15:19:21,2013-01-01T15:19:21,2013-01-01
3,4,T01117247,A00003818,Credit,Credit in Cash,600.0,600.0,NaN,NaN,NaN,2013,1,1,2013-01-01,10:42:35,2013-01-01T10:42:35,2013-01-01
4,5,T00579373,A00001972,Credit,Credit in Cash,400.0,400.0,NaN,NaN,NaN,2013,1,2,2013-01-02,11:39:25,2013-01-02T11:39:25,2013-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056315,1056316,T03626622,A00002906,Credit,NaN,62.3,13729.4,Interest Credited,NaN,NaN,2018,12,31,2018-12-31,15:18:14,2018-12-31T15:18:14,2018-12-31
1056316,1056317,T03627616,A00002935,Credit,NaN,81.3,19544.9,Interest Credited,NaN,NaN,2018,12,31,2018-12-31,13:04:60,2018-12-31T13:04:60,2018-12-31
1056317,1056318,T03625403,A00002869,Credit,NaN,60.2,14638.2,Interest Credited,NaN,NaN,2018,12,31,2018-12-31,08:30:13,2018-12-31T08:30:13,2018-12-31
1056318,1056319,T03626683,A00002907,Credit,NaN,107.5,23453.0,Interest Credited,NaN,NaN,2018,12,31,2018-12-31,14:45:19,2018-12-31T14:45:19,2018-12-31
1056319,1056320,T03626540,A00002902,Credit,NaN,164.1,41642.9,Interest Credited,NaN,NaN,2018,12,31,2018-12-31,10:44:40,2018-12-31T10:44:40,2018-12-31

In [ ]:
credit_trans_df = completed_trans_df[(completed_trans_df['type'] == 'Credit') & (completed_trans_df['operation'] != 'Collection from Another Bank') \
                                     & (completed_trans_df['bank'].isna())].groupby(by=['account_id','type']).agg({'amount': 'sum', 'trans_id':'count'}).reset_index()
credit_trans_df.rename(columns={'trans_id': 'trans_count', 'amount': 'amount_credit'}, inplace=True)

In [ ]:
credit_trans_df

     account_id    type  amount_credit  trans_count
0     A00000001  Credit        28765.5           57
1     A00000002  Credit        59117.5           82
2     A00000003  Credit       173059.0           46
3     A00000004  Credit         3544.0           31
4     A00000005  Credit         2162.0           16
...         ...     ...            ...          ...
4495  A00011333  Credit      1677057.6          183
4496  A00011349  Credit        22239.2           48
4497  A00011359  Credit        12364.2           53
4498  A00011362  Credit       684270.7           81
4499  A00011382  Credit        11226.5           81

[4500 rows x 4 columns]

In [ ]:
credit_trans_df['type'].value_counts()

KeyError: 'type'

In [ ]:
completed_loan_df.rename(columns={'amount': 'amount_loan', 'payment': 'payment_loan', 'status': 'status_loan', 'purpose': 'purpose_loan'}, inplace=True)

In [ ]:
final_df = pd.merge(credit_trans_df, completed_loan_df, on='account_id', how='outer')
final_df = pd.merge(final_df, trans_last_synthesis_df[['account_id', 'balance_last','diff_date']], on='account_id', how='inner')

In [ ]:
final_df.to_csv('/content/drive/MyDrive/workspace/VPBank_Hackathon/src/data_preprocessing/data_clv.csv', index=False)

## Tá»•ng há»£p dá»¯ liá»‡u

In [ ]:
completed_acct_df.head(5)

  account_id  district_id         frequency  parseddate  year  month  day
0  A00000576           55  Monthly Issuance  2013-01-01  2013      1    1
1  A00003818           74  Monthly Issuance  2013-01-01  2013      1    1
2  A00000704           55  Monthly Issuance  2013-01-01  2013      1    1
3  A00002378           16  Monthly Issuance  2013-01-01  2013      1    1
4  A00002632           24  Monthly Issuance  2013-01-02  2013      1    2

In [ ]:
completed_disposition_df.head(5)

     disp_id  client_id account_id   type
0  D00000001  C00000001  A00000001  Owner
1  D00000002  C00000002  A00000002  Owner
2  D00000003  C00000003  A00000002   User
3  D00000004  C00000004  A00000003  Owner
4  D00000005  C00000005  A00000003   User

In [ ]:
columns_cluster_used = ['client_id', 'age', 'state', 'city', 'district_id', 'sex']
client_df_used = completed_client_df[columns_cluster_used]
dispostion_client_df = pd.merge(completed_disposition_df, client_df_used, on='client_id', how='outer', suffixes=('_disposition', '_client'))

In [ ]:
dispostion_client_df

,disp_id,client_id,account_id,type,age,state,city,district_id,sex
0,D00000001,C00000001,A00000001,Owner,29,NM,Albuquerque,18,Female
1,D00000002,C00000002,A00000002,Owner,54,NY,New York City,1,Male
2,D00000003,C00000003,A00000002,User,59,NY,New York City,1,Female
3,D00000004,C00000004,A00000003,Owner,43,IN,Indianapolis,5,Male
4,D00000005,C00000005,A00000003,User,39,IN,Indianapolis,5,Female
...,...,...,...,...,...,...,...,...,...
5364,D00013647,C00013955,A00011349,Owner,54,NY,New York City,1,Female
5365,D00013648,C00013956,A00011349,User,56,NY,New York City,1,Male
5366,D00013660,C00013968,A00011359,Owner,31,MA,Fall River,61,Male
5367,D00013663,C00013971,A00011362,Owner,37,CT,Danbury,67,Female
5368,D00013690,C00013998,A00011382,Owner,46,IL,Chicago,74,Female

In [ ]:
card_dispostion_client_df = pd.merge(dispostion_client_df, completed_card_df, on='disp_id', how='outer', suffixes=('', '_card'))

In [ ]:
card_dispostion_client_df

,disp_id,client_id,account_id,type,age,state,city,district_id,sex,card_id,type_card,year,month,day,fulldate
0,D00000001,C00000001,A00000001,Owner,29,NM,Albuquerque,18,Female,NaN,NaN,NaN,NaN,NaN,NaN
1,D00000002,C00000002,A00000002,Owner,54,NY,New York City,1,Male,NaN,NaN,NaN,NaN,NaN,NaN
2,D00000003,C00000003,A00000002,User,59,NY,New York City,1,Female,NaN,NaN,NaN,NaN,NaN,NaN
3,D00000004,C00000004,A00000003,Owner,43,IN,Indianapolis,5,Male,NaN,NaN,NaN,NaN,NaN,NaN
4,D00000005,C00000005,A00000003,User,39,IN,Indianapolis,5,Female,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,D00013647,C00013955,A00011349,Owner,54,NY,New York City,1,Female,NaN,NaN,NaN,NaN,NaN,NaN
5365,D00013648,C00013956,A00011349,User,56,NY,New York City,1,Male,NaN,NaN,NaN,NaN,NaN,NaN
5366,D00013660,C00013968,A00011359,Owner,31,MA,Fall River,61,Male,V00001247,VISA Signature,2015.0,6.0,13.0,2015-06-13
5367,D00013663,C00013971,A00011362,Owner,37,CT,Danbury,67,Female,NaN,NaN,NaN,NaN,NaN,NaN
5368,D00013690,C00013998,A00011382,Owner,46,IL,Chicago,74,Female,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_df

,account_id,type,amount_credit,trans_count,loan_id,amount_loan,duration,payments,status_loan,year,month,day,fulldate,location,purpose_loan,balance_last,diff_date
0,A00000001,Credit,28765.5,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13466.5,1378
1,A00000002,Credit,59117.5,82,L00004959,80952.0,24.0,3373.0,A,2014.0,1.0,5.0,2014-01-05,1.0,home,42628.1,2134
2,A00000003,Credit,173059.0,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51096.1,542
3,A00000004,Credit,3544.0,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33720.7,1044
4,A00000005,Credit,2162.0,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28088.3,580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,A00011333,Credit,1677057.6,183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58319.0,1680
4496,A00011349,Credit,22239.2,48,L00007304,419880.0,60.0,6998.0,C,2015.0,10.0,29.0,2015-10-29,1.0,home,33977.9,1315
4497,A00011359,Credit,12364.2,53,L00007305,54024.0,12.0,4502.0,A,2016.0,8.0,6.0,2016-08-06,1.0,home,75200.4,1552
4498,A00011362,Credit,684270.7,81,L00007308,129408.0,24.0,5392.0,A,2016.0,12.0,27.0,2016-12-27,1.0,home,38530.6,1174
4499,A00011382,Credit,11226.5,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81674.7,1229

In [197]:
account_client_merge = pd.merge(card_dispostion_client_df, final_df, on='account_id', how='inner', suffixes=('', '_trans'))
data = pd.merge(cash_in_df, account_client_merge, on='account_id', how='outer')
data = pd.merge(cash_out_df, data, on='account_id', how='outer')

In [ ]:
account_client_merge

,disp_id,client_id,account_id,type,age,state,city,district_id,sex,card_id,...,payments,status_loan,year_trans,month_trans,day_trans,fulldate_trans,location,purpose_loan,balance_last,diff_date
0,D00000001,C00000001,A00000001,Owner,29,NM,Albuquerque,18,Female,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13466.5,1378
1,D00000002,C00000002,A00000002,Owner,54,NY,New York City,1,Male,NaN,...,3373.0,A,2014.0,1.0,5.0,2014-01-05,1.0,home,42628.1,2134
2,D00000003,C00000003,A00000002,User,59,NY,New York City,1,Female,NaN,...,3373.0,A,2014.0,1.0,5.0,2014-01-05,1.0,home,42628.1,2134
3,D00000004,C00000004,A00000003,Owner,43,IN,Indianapolis,5,Male,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51096.1,542
4,D00000005,C00000005,A00000003,User,39,IN,Indianapolis,5,Female,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51096.1,542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,D00013647,C00013955,A00011349,Owner,54,NY,New York City,1,Female,NaN,...,6998.0,C,2015.0,10.0,29.0,2015-10-29,1.0,home,33977.9,1315
5365,D00013648,C00013956,A00011349,User,56,NY,New York City,1,Male,NaN,...,6998.0,C,2015.0,10.0,29.0,2015-10-29,1.0,home,33977.9,1315
5366,D00013660,C00013968,A00011359,Owner,31,MA,Fall River,61,Male,V00001247,...,4502.0,A,2016.0,8.0,6.0,2016-08-06,1.0,home,75200.4,1552
5367,D00013663,C00013971,A00011362,Owner,37,CT,Danbury,67,Female,NaN,...,5392.0,A,2016.0,12.0,27.0,2016-12-27,1.0,home,38530.6,1174
5368,D00013690,C00013998,A00011382,Owner,46,IL,Chicago,74,Female,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81674.7,1229

In [198]:
data['is_has_loan'] = data['loan_id'].apply(lambda x: 1 if not pd.isna(x) else 0)
data['is_has_card'] = data['card_id'].apply(lambda x: 1 if not pd.isna(x) else 0)

In [199]:
data.columns

Index(['account_id', 'amount_cash_out', 'trans_cash_out_count',
       'amount_cash_in', 'trans_cash_in_count', 'disp_id', 'client_id', 'type',
       'age', 'state', 'city', 'district_id', 'sex', 'card_id', 'type_card',
       'year', 'month', 'day', 'fulldate', 'type_trans', 'amount_credit',
       'trans_count', 'loan_id', 'amount_loan', 'duration', 'payments',
       'status_loan', 'year_trans', 'month_trans', 'day_trans',
       'fulldate_trans', 'location', 'purpose_loan', 'balance_last',
       'diff_date', 'is_has_loan', 'is_has_card'],
      dtype='object')

In [200]:
data.head()

,account_id,amount_cash_out,trans_cash_out_count,amount_cash_in,trans_cash_in_count,disp_id,client_id,type,age,state,...,year_trans,month_trans,day_trans,fulldate_trans,location,purpose_loan,balance_last,diff_date,is_has_loan,is_has_card
0,A00000001,263635.0,85.0,111539.5,154,D00000001,C00000001,Owner,29,NM,...,NaN,NaN,NaN,NaN,NaN,NaN,13466.5,1378,0,0
1,A00000002,2091170.8,159.0,1060308.5,319,D00000002,C00000002,Owner,54,NY,...,2014.0,1.0,5.0,2014-01-05,1.0,home,42628.1,2134,1,0
2,A00000002,2091170.8,159.0,1060308.5,319,D00000003,C00000003,User,59,NY,...,2014.0,1.0,5.0,2014-01-05,1.0,home,42628.1,2134,1,0
3,A00000003,65013.0,39.0,230008.8,78,D00000004,C00000004,Owner,43,IN,...,NaN,NaN,NaN,NaN,NaN,NaN,51096.1,542,0,0
4,A00000003,65013.0,39.0,230008.8,78,D00000005,C00000005,User,39,IN,...,NaN,NaN,NaN,NaN,NaN,NaN,51096.1,542,0,0

In [ ]:
columns_cluster_final_used = ['client_id', 'account_id', 'age', 'state', 'city', 'district_id', 'sex', 'balance_last', 'diff_date', 'trans_count', 'amount_loan','amount_credit', 'is_has_loan', 'is_has_card']

In [202]:
data.to_csv('/content/drive/MyDrive/workspace/VPBank_Hackathon/src/data_preprocessing/data_train_ver2.csv', index=False)